prototype:ScriptProcessorNode 
alert ("soma55");
HTMLFormControlsCollection
alert ("menos45");
alert ("diferente45")
IdleDeadline
console.log();
function soma(valor1, valor2){
    function realpara dolar (real, cotaçao dolar
    return real) + cotacaodolar
}

var valoreal = 7.89
var cotacao =5.88


var total = realparadolar(5.69,10)

alert(total)

{
    MouseEvent
    let 
/**
* 
*/
    name() {
 localStorage  
 function
 mouse up 
 mouse down 
    
 } while (condition);
   
}
}